### ISSUE TITLE
about CIFAR10 part  main.py resume function

### ISSUE THREAD

**Issue by lxy21319** [yhhhli/APoT_Quantization#16]
i found that  maybe  in  CIFAR10 part  main.py  ,the resume function was not defined

**Comment by yhhhli** [comment]
hi,

sorry about this, for the resume function, you can directly use examples in other pytorch CIFAR examples. The model can be safely saved and loaded in the official pytorch function.

Thanks.

**Comment by lxy21319** [comment]
Thanks a lot
