### ISSUE TITLE
Bottleneck Doubts

### ISSUE THREAD

**Issue by dronefreak** [yhhhli/APoT_Quantization#3]
This is more like a doubt and less like an issue. I am new to this field, so I am unable to understand, why the QuantConv() layers have not been implemented in the Bottleneck class. Only the BasicBlock witnesses the usage of the quantized convolutional layers.
Is there a specific reason for that? Does it affect the accuracy too much?

**Comment by yhhhli** [comment]
Hello, 
BottleNeck block is the components of ResNet-50 or higher, (like ResNet-152). For ResNet-18 and 34, we only need to quantize the Basic block.
I will provide codes and checkpoints later for ResNet-50. Please check for our updates!
